services:
  # Message Broker for communication
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Main Database Instance
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cqrs_admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #pgadmin:
  #  image: elestio/pgadmin
  #  container_name: pgadmin
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #    PGADMIN_DEFAULT_PASSWORD: password
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - db

  user-service:
    build: ./services/user-service
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - DATABASE_HOST=db
      - POSTGRES_USER=cqrs_admin
      - POSTGRES_PASSWORD=password123
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq

volumes:
  rabbitmq_data:
  postgres_data: